
apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  labels:
    backup.appconnect.ibm.com/component: integrationruntime
  name: ir-R1-dev
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-XRNH-47FJAW
    use: CloudPakForIntegrationNonProductionFREE
  replicas: 1
  template:
    spec:
      containers:
        - name: runtime
          resources:
            requests:
              cpu: 300m
              memory: 368Mi
  version: 12.0.12-r4
  barURL: 
    - https://github.com/junshen1969/acedeploy/raw/main/R1/dev/bar/integration.bar
  configurations: 
    - barauth-config

